### ISSUE TITLE
Exception thrown by python: NameError: global name '_' is not defined

### ISSUE THREAD

**Issue by mojca** [wbsoft/frescobaldi#843] opened 2016-07-28 13:59 UTC
When I try to run frescobaldi 2.19.0 for the first time, it ends with an exception:

~~~
Traceback (most recent call last):
  File "/opt/local/bin/frescobaldi", line 13, in <module>
    main.main()                     # Parse command line, create windows etc
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/main.py", line 185, in main
    args = parse_commandline()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/main.py", line 53, in parse_commandline
    argparse._ = _ # let argparse use our translations
NameError: global name '_' is not defined
~~~

This is on OS X (installed via MacPorts). I tried using both system python and python provided by the package manager.

**Comment by dliessi** [comment] 2016-07-29 07:41
I cannot reproduce this on two different machines.
@wbsoft Do you have any idea?

**Comment by mojca** [comment] 2016-07-29 21:19
It's a stupid thought, but what happens if the user's locale is not supported by Frescobaldi?

Where could I start debugging the problem?

**Comment by dliessi** [comment] 2016-07-30 08:54
@mojca Could you please try the [prebuilt application bundle](https://github.com/wbsoft/frescobaldi/releases/tag/v2.19.0) and check if it also crashes?
(You might encounter #428 with that.)
Error messages should appear in the Console application, if I remember correctly.

**Comment by mojca** [comment] 2016-07-30 13:39
The prebuilt application works fine.

**Comment by dliessi** [comment] 2016-08-01 21:29
@mojca Do you have any dependency of Frescobaldi installed with non default variants? In that case, can you post the relevant information?

I'm quite convinced that your problem is specific to your setup, given that Frescobaldi runs without errors in every system I tried.

**Comment by mojca** [comment] 2016-08-01 21:47
I don't see anything obvious:

`poppler-qt4-mac @0.46.0_0 (active)`
`portmidi @217_1 (active)`
`py27-poppler-qt4 @0.24.0_0 (active)`
`py27-pyqt4 @4.11.4_4 (active)`
`py27-sip @4.18_0 (active)`
`py27-ly @0.9.4_0 (active)`
`qt4-mac @4.8.7_4 (active)`

- I have
  `port select python python35`
  but even if I switch it to python27, it doesn't make any difference
- I have
  `py27-readline`
  installed, but deactivating it didn't help.
- I have
  `cairo @1.14.6_0+quartz+x11 (active)`
  `pango @1.40.1_0+quartz+x11 (active)`
  but I don't understand how that could possibly affect the observed behaviour.
- I have
  `lilypond-devel @2.19.44_0 (active)`,
compiled with gcc 5 or 6. But again I don't understand what lilypond would have to do with failing python code.

If you have any idea which ports to check, let me know. The list of dependencies is long (and I don't remember doing any changes on any of them) and it's not obvious to me what could have made any difference.

**Comment by mojca** [comment] 2016-08-01 22:28
Can someone please explain me where exactly the underscore (`_`) gets defined?

I checked and the code inside
~~~
@app.oninit
def _start_up():
~~~
in `po.setup` gets executed. The language is `en_GB` and `_setup()` returns `install(None)` because `mo = find(language)` doesn't return anything.

But even if I change the language manually to
~~~
language = "de"
~~~
then it finds `/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/po/de.mo`, but `_` is still undefined.

**Comment by mojca** [comment] 2016-08-01 23:30
@dliessi: can you please try
~~~
sudo port install py27-future
~~~
and then run frescobaldi again?

This could be the source of the problem:
~~~
.../python2.7/site-packages/builtins
.../python2.7/site-packages/builtins/__init__.py
.../python2.7/site-packages/builtins/__init__.pyc
.../python2.7/site-packages/future/builtins
.../python2.7/site-packages/future/builtins/__init__.py
.../python2.7/site-packages/future/builtins/__init__.pyc
~~~

The problem seems to be in [this line](https://github.com/wbsoft/frescobaldi/blob/0c1d242350ef07f571afcec5b7cc8ae5c34e25f3/frescobaldi_app/po/__init__.py#L77). In the bundled Frescobaldi there are no surprizes at all. But in MacPorts, builtins from future seems to be prioritized when loading
~~~
import __builtin__ as builtins
~~~

This is a somewhat moot point however now that the latest Frescobaldi no longer supports Python 2. The released versions do though. From the perspective of MacPorts, we should support Python 3 rather than just hardcode Python 2. I have to check whether it work with 3.5.

**Comment by dliessi** [comment] 2016-08-02 09:04
The problem is indeed `py27-future`: I installed it and got the same error you reported.
I can see two possible solutions:
1. declare `frescobaldi(-devel)` conflicting with `py27-future` in MacPorts;
2. switch `frescobaldi(-devel)` to Python 3.
Probably the second one is better.
@mojca What do you think?

> From the perspective of MacPorts, we should support Python 3 rather than just hardcode Python 2.

I considered this, but Frescobaldi has been supporting both Python 2 and 3 only for the few latest versions and will drop support for Python 2 in the upcoming version 3 (although that does not mean that it will stop working with Python 2).
Hence I thought it wasn't worth supporting both Pythons.
Anyway, I can add the necessary variants.

> I have to check whether it works with 3.5.

It does.

**Comment by mojca** [comment] 2016-08-02 09:22
If you want simplicity, you could switch to Python 3 exclusively, that's up to you.

But you could probably provide two (or more) variants with `+python27`, `+python35`, ... and make `frescobaldi +python27` conflict with `py27-future`. (Python 3.5 doesn't compile out of the box on 10.7, but `configure.compiler` does the trick.)

Frescobaldi with python 3.5 didn't launch the first time I opened it (not even the usual trick to click the icon etc. as described in #428 helped). But it did work the second time.

Judging from the source code I guess that the new version won't work with Python 2 at all. At the moment you have the block that says "if this is Python >= 3, do this, else do that" and in master this is gone with a comment "we know that we are in Python 3".

(The main developers should tell, but I don't believe there is anything that could be done in the source code to avoid the reported problem.)

**Comment by dliessi** [comment] 2016-08-02 09:36
> Judging from the source code I guess that the new version won't work with Python 2 at all. At the moment you have the block that says "if this is Python >= 3, do this, else do that" and in master this is gone with a comment "we know that we are in Python 3".

Yes, indeed, I didn't remember exactly and didn't check before writing.

I don't want to add variants for various Pythons just for one version of Frescobaldi and remove them for the next.
But should I add variants for different versions of Python 3? I had the impression that in MacPorts we don't want to let different versions of the same programming language proliferate again, so I might keep only the latest supported Python 3 version.
But this:

> (Python 3.5 doesn't compile out of the box on 10.7, but `configure.compiler` does the trick.)

suggests that maybe a Python 3.4 variant would be useful on 10.7.
@mojca What do you think?

**Comment by mojca** [comment] 2016-08-02 10:29
No, this suggests that we should fix the Python 3.5 port, not that we should come up with ugly workarounds just for Xcode 4 for every single dependent of Python.

* https://trac.macports.org/ticket/49272
* https://bugs.python.org/issue24844#msg256214

I would have committed a fix to blacklist the compiler already, I guess I was hoping that me or someone else could come up with an idea for a proper upstream fix (this way I get reminded that Python is broken each time when the port gets updated :). Don't bother special-casing 10.7. Just support the latest python, that's it.

If you add python variants now, you could potentially keep `+python35` and `+python36` for the next version of Frescobaldi. But even if you drop the variants later, I don't see a problem at all. You are the maintainer though, so it's up to you. Plus, maybe this discussion should continue on the MacPorts tracker. We're getting way too off-topic here.

**Comment by dliessi** [comment] 2016-08-02 10:47
I think I'll stick with only the latest Python 3.

> Plus, maybe this discussion should continue on the MacPorts tracker. We're getting way too off-topic here.

Indeed.
I'll close this issue since it is not a bug in Frescobaldi, and I'll write a summary of the findings in [the MacPorts ticket](https://trac.macports.org/ticket/51931).

**Closed by dliessi** 2016-08-02 10:47 UTC

**Comment by wbsoft** [comment] 2016-08-03 12:02
I did not completely follow the discussion, but Frescobaldi `v2.x` branch should work with both python 2 and 3. The `master` branch is only tested with Python 3 and will also use features that are new in Python 3.

**Comment by wbsoft** [comment] 2016-10-01 08:44
Dear friends, I did not completely understand how it comes that the definition of `_` fails. Is there anything I can do to Frescobaldi to remove the conflict with python2.7's future? I would like Frescobaldi 2.20 to be a viable Frescobaldi version that still fully supports Python 2.7 without problems.

**Comment by mojca** [comment] 2016-10-04 00:20
My installed frescobaldi no longer uses python 2.7 (I can try to switch back to it though), so I created a minimal example that fails in the same way:
~~~
try:
    import builtins # py3
except ImportError:
    import __builtin__ as builtins # py2

builtins._ = "hello"
a = _
~~~

The problem is that whenever `py27-future` module is installed, this will load `import builtins`. It works if I leave a plain import of `__builtin__` and change the code to the following:
~~~
import __builtin__ as builtins
builtins._ = "hello"
a = _
~~~

I assume that the following should work properly:
~~~
import sys
if sys.version_info >= (3, 0):
    import builtins # py3
else:
    import __builtin__ as builtins # py2
~~~

**Comment by wbsoft** [comment] 2017-02-14 12:34
Looking into this, I can say that the 2.x line of Frescobaldi should support Python 2.7+ and 3, so indeed we should try to fix/workaround this.

**Comment by wbsoft** [comment] 2017-02-14 12:47
I applied the workaround in the `v2.x` branch (where this is relevant)
