### ISSUE TITLE
Python package missing on Mac?

### ISSUE THREAD

**Issue by brumleygap** [wbsoft/frescobaldi#778] opened 2015-11-08 21:47 UTC
Installed Frescobaldi on Mac OSX 10.11.1 using brew, but I get this error:
ImportError: No module named sip

Ernie-Air:~ erniebraganza$ brew update
Already up-to-date.
Ernie-Air:~ erniebraganza$ brew install frescobaldi --without-lilypond
==> Downloading https://github.com/wbsoft/frescobaldi/releases/download/v2.18.1/
Already downloaded: /Library/Caches/Homebrew/frescobaldi-2.18.1.tar.gz
==> Downloading https://github.com/wbsoft/python-poppler-qt4/archive/v0.18.1.tar
Already downloaded: /Library/Caches/Homebrew/frescobaldi--python-poppler-qt4-0.18.1.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cel
==> Downloading https://pypi.python.org/packages/source/p/python-ly/python-ly-0.
Already downloaded: /Library/Caches/Homebrew/frescobaldi--python-ly-0.9.2.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cel
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cel
==> Caveats
By default, a splash screen is shown on startup; this causes the main
window not to show until the application icon on the dock is clicked
(Cmd-Tab application switching does not appear to work).

You may want to disable the splash screen in the preferences to
solve this issue. See:
  https://github.com/wbsoft/frescobaldi/issues/428
==> Summary
🍺  /usr/local/Cellar/frescobaldi/2.18.1: 1136 files, 14M, built in 29 seconds
Ernie-Air:~ erniebraganza$ frescobaldi
Traceback (most recent call last):
  File "/usr/local/Cellar/frescobaldi/2.18.1/libexec/bin/frescobaldi", line 7, in <module>
    import main
  File "/usr/local/Cellar/frescobaldi/2.18.1/libexec/lib/python2.7/site-packages/frescobaldi_app/main.py", line 26, in <module>
    import sip
ImportError: No module named sip
Ernie-Air:~ erniebraganza$

**Comment by dliessi** [comment] 2015-11-09 09:01
This is almost surely a bug in your setup or, less probably, in Homebrew:

* `frescobaldi` and `python-poppler-qt4` (installed by the same formula) and `pyqt` require `sip`;
* `sip` is correctly declared as dependency of `pyqt` (see [`pyqt.rb`](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/pyqt.rb#L23));
* `pyqt` is correctly declared as dependency of `frescobaldi`/`python-poppler-qt4` (see [`frescobaldi.rb`](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/frescobaldi.rb#L22));

so `sip` should be correctly installed when you run `frescobaldi`.

Please see [Homebrew's troubleshooting instructions](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting).

I'll close this issue for now: in case the problem turns out to be actually in Frescobaldi, feel free to reopen it (and please give us further details).

**Closed by dliessi** 2015-11-09 09:01 UTC

**Comment by wjlafrance** [comment] 2016-02-06 08:10
Hello, just came here from Google with the same error related to finding `sip`. The packages you mentioned were all installed (except python-poppler-qt4 which appears gone now).

It turns out my problem (and possibly the original problem) is covered in caveats of `sip`.

	==> Caveats
	The sip-dir for Python is /usr/local/share/sip.

	Python modules have been installed and Homebrew's site-packages is not
	in your Python sys.path, so you will not be able to import the modules
	this formula installed. If you plan to develop with these modules,
	please run:
	  mkdir -p /Users/lafrance/Library/Python/2.7/lib/python/site-packages
	  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/lafrance/Library/Python/2.7/lib/python/site-packages/homebrew.pth

I won't re-open this issue, but you might want to add something about this to `frescobaldi`'s caveats.

**Comment by dliessi** [comment] 2016-02-07 19:58
This confirms that the problem with `sip` is not on our side.

I don't use Homebrew, but I understand that "caveats" are instructions to the user that are printed when installing a package.
If this is correct, then the solution to the problem is already given to the user when `sip` gets installed.

> except python-poppler-qt4 which appears gone now

Do you mean that `python-poppler-qt4` is not actually installed (i.e., its files are not on your system and you don't have PDF preview in Frescobaldi) or that it is not listed as an installed package by Homebrew?
As far as I understand that latter should be expected.

**Comment by wjlafrance** [comment] 2016-02-08 00:59
`python-poppler-qt4` seems to not exist in brew anymore. But I do have PDF preview in Frescobaldi, so I'm sure it's a non-issue.

So it does seem this isn't an issue in Frescobaldi, but I can see how other users would make the same mistake I made. If I sent in a PR adding "You may need to link brew-installed Python packages. See #778" would you be against merging it?

**Comment by dliessi** [comment] 2016-02-08 09:06
> `python-poppler-qt4` seems to not exist in brew anymore. But I do have PDF preview in Frescobaldi, so I'm sure it's a non-issue.

Ok, if PDF preview is working, then `python-poppler-qt4` is installed and works correctly.
It has never been available as a separate Homebrew formula, but is installed as part of Frescobaldi's installation (see [frescobaldi.rb](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/frescobaldi.rb#L24)).
So it is normal that it is not listed by the `brew` command.

> That would go in brew, not here, so I'll submit over there.

Indeed. Thanks for reporting, anyway.
