### ISSUE TITLE
internal error when opening or rendering any .ly file

### ISSUE THREAD

**Issue by shimpe** [wbsoft/frescobaldi#838] opened 2016-07-01 20:33 UTC
Any ideas as to what might cause this? Some incompatibility between libraries perhaps?
The url parameter that causes the TypeError pretends to be of type PyQt5.QtCore.QStorageInfo, but whatever method I try to call on it causes bad things to happen (segmentation faults).

VERSIONS: 

Frescobaldi: 3.0.0 (latest git master)
Python: 3.5.1
python-ly: 0.9.4 (latest git)
Qt: 5.6.0
PyQt: 5.6
sip: 4.18
poppler: 0.42.0
python-poppler-qt: 0.24.1
OS: Linux-4.6.3-1-ARCH-x86_64-with-arch

BACKTRACE:

Traceback (most recent call last):
  File "/home/shimpe/development/python/frescobaldi/frescobaldi/frescobaldi_app/musicview/pointandclick.py", line 44, in links
    return _cache[document]
  File "/usr/lib/python3.5/weakref.py", line 365, in __getitem__
    return self.data[ref(key)]
KeyError: <weakref at 0x7f955f2afae8; to 'Document' at 0x7f95600f09d8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shimpe/development/python/frescobaldi/frescobaldi/frescobaldi_app/musicview/widget.py", line 116, in openDocument
    self._links = pointandclick.links(document)
  File "/home/shimpe/development/python/frescobaldi/frescobaldi/frescobaldi_app/musicview/pointandclick.py", line 54, in links
    t = textedit.link(link.url())
  File "/home/shimpe/development/python/frescobaldi/frescobaldi/frescobaldi_app/textedit.py", line 48, in link
    m = textedit_match(url)
TypeError: expected string or bytes-like object

**Comment by wbsoft** [comment] 2016-07-02 17:31
thanks for reporting

**Comment by anthonyfok** [comment] 2016-10-05 12:41
Just to chime in: I am seeing the exact same error on Debian, with master checked out today (2016-10-01), when I press Ctrl-M to render a new music score for "Engrave (preview)":

Frescobaldi: 3.0.0 -- Python: 3.5.2+ -- python-ly: 0.9.4 -- Qt: 5.6.1 -- PyQt: 5.7 -- sip: 4.18.1 -- poppler: 0.38.0 -- python-poppler-qt: 0.24.2 -- OS: Linux-4.7.0-1-amd64-x86_64-with-debian-stretch-sid

```
Traceback (most recent call last):
  File "/work/git/frescobaldi/frescobaldi_app/musicview/pointandclick.py", line 44, in links
    return _cache[document]
  File "/usr/lib/python3.5/weakref.py", line 365, in __getitem__
    return self.data[ref(key)]
KeyError: <weakref at 0x7f8430ee3818; to 'Document' at 0x7f8493fe7798>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/git/frescobaldi/frescobaldi_app/musicview/widget.py", line 116, in openDocument
    self._links = pointandclick.links(document)
  File "/work/git/frescobaldi/frescobaldi_app/musicview/pointandclick.py", line 54, in links
    t = textedit.link(link.url())
  File "/work/git/frescobaldi/frescobaldi_app/textedit.py", line 48, in link
    m = textedit_match(url)
TypeError: expected string or bytes-like object
```

Many thanks!

**Comment by anthonyfok** [comment] 2016-10-05 23:26
It might have to do with a breaking ABI change in SIP that, at the moment, requires a rebuild of python3-poppler-qt5, according to these Debian bug report:

* https://bugs.debian.org/839870
* https://bugs.debian.org/839875

I will report back once I have more information, i.e. to see if this bug goes away after a rebuild of python3-poppler-qt5.

**Comment by anthonyfok** [comment] 2016-10-06 05:03
@shimpe, the error message is caused by an ABI incompatibility between "sip: 4.18" and "python-poppler-qt: 0.24.1" that was built with an earlier version of sip.  A rebuild of python-poppler-qt5 should fix the problem for you.  So, you may either do it yourself, or bug the Arch Linux developers to do so.  :-)

See https://www.riverbankcomputing.com/pipermail/pyqt/2016-September/038136.html for an explanation from a PyQt developer.  Heads up: It is going to happen again soon when SIP v4.19 is released!

Ditto for Debian: Debian stretch/sid (testing/unstable) users began experiencing the same problem as of early October 2016 (and perhaps earlier).  It has nothing to do with Frescobaldi itself.  Rather, it is the aforementioned ABI incompatibility between python-poppler-qt5 and the sip-dev/python3-sip-dev library that is the culprit.  Rebuilding the python-poppler-qt5 package solves the problem.

I have just done exactly that, and uploaded a new `python3-poppler-qt5` package to the Debian FTP repository.  For affected users, upgrading to `python3-poppler-qt5` version 0.24.2-2 should fix the problem.

```
python-poppler-qt5 (0.24.2-2) unstable; urgency=high

  [ Ondřej Nový ]
  * Fixed VCS URL (https)

  [ Anthony Fok ]
  * Cherry upstream fixes since the 0.24.2 release
  * Refresh debian/control
    - Bump Standards-Version to 3.9.8
    - Tweak Vcs-Browser according to https://wiki.debian.org/Python/GitPackaging
  * This new build incidentally solves an ABI incompatibility with the
    recently updated SIP library: was sip-py3api-11.2, now sip-py3api-11.3.
    (Closes: #839875, #839870)

 -- Anthony Fok <foka@debian.org>  Wed, 05 Oct 2016 22:25:56 -0600
```

@wbsoft, please close this issue (a false alarm) when you are free.  :-)

**Comment by shimpe** [comment] 2016-10-06 06:17
@anthonyfok Thanks for getting to the bottom of this.

**Comment by uliska** [comment] 2016-12-07 08:16
I have just installed Debian testing and run Frescobaldi with the following components:

```
Frescobaldi: 3.0.0
Python: 3.5.2+
python-ly: 0.9.4
Qt: 5.7.1
PyQt: 5.7
sip: 4.18.1
poppler: 0.44.0
python-poppler-qt: 0.24.2
OS: Linux-4.7.0-1-amd64-x86_64-with-debian-stretch-sid
```
Despite having `python-poppler-qt` in version 0.24.2 I experience exactly this error.
So it seems it's *not* completely solved yet?

**Comment by uliska** [comment] 2016-12-09 09:48
In addition, for *some* documents (I don't see what's the difference) Frescobaldi actually *crashes* (i.e. simply closes the window) with the following message in the terminal:

```
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
/home/uliska/bin/frescobaldi: Zeile 2:  7995 Speicherzugriffsfehler 
PYTHONPATH=$PYTHONPATH:~/git/lilypond/python-ly python3 
~/git/lilypond/frescobaldi/frescobaldi $@
```

**Comment by uliska** [comment] 2016-12-09 11:24
The crash (instead of the caught and displayed Python exception) happens when a file includes `"lilypond-book-preamble.ly"` 

A differenc I can see is that in this case  there are more than one resulting PDF documents.

**Comment by anthonyfok** [comment] 2016-12-16 20:22
Hi @uliska,

> Despite having `python-poppler-qt` in version 0.24.2 I experience exactly the same error.
> So it seems it's not _completely_ solved yet?

Thank you for reporting this.  I think it may have to do with Debian's transition from Qt 5.6 to Qt 5.7 that happened a month and a half ago (early November).  I happened to be preparing to package Frescobaldi 3.0.0 pre-release for Debian unstable (freeze coming soon), and ran into the same `TypeError: expected string or bytes-like object` error.

Fortunately, recompiling `python-poppler-qt5` does the trick, and a new version has been uploaded to Debian unstable:

```
python-poppler-qt5 (0.24.2-3) unstable; urgency=high

  * Fix a typo of "highlight" in poppler-annotation.sip
  * Rebuild to fix a hidden (?) ABI incompatibility, probably with
    the recent upgrade to qtbase-abi-5-7-1.

 -- Anthony Fok <foka@debian.org>  Thu, 15 Dec 2016 16:13:18 -0700
```

It won't enter Debian testing for another 10 days (?), so please install `python3-poppler-qt5` 0.24.2-3 from unstable: https://packages.debian.org/sid/python3-poppler-qt5

I do not yet know how to get `dpkg-shlibdeps` or related tools to discover that python3-poppler-qt5` needs to depends on the virtual `qtbase-abi-5-7-1` package like `python3-pyqt5` does, but I intend to look into it in the not-too-distant future.

**Comment by fedelibre** [comment] 2016-12-18 14:15
I've run into the same problem. As there's no `python3-poppler-qt5` in Fedora yet, I recompiled the package from source following [these instructions](https://github.com/wbsoft/python-poppler-qt5/issues/8#issuecomment-228308836).

**Comment by uliska** [comment] 2016-12-22 09:38
I can confirm that reinstalling `python3-poppler-qt5` from source (I also needed the instructions referenced by @fedelibre to make it work) seems to fix the problem here.

I hope this is an issue for people running Frescobaldi from Git only and won't bleed into releases.

**Comment by uliska** [comment] 2016-12-22 09:39
As I had re-opened the issue I'll re-close it again, now that *my* problem seems to have been resolved. Still assume we'll have to keep an eye on the issue.

**Closed by uliska** 2016-12-22 09:39 UTC

**Comment by shimpe** [comment] 2016-12-22 20:50
For people using arch linux, rebuilding python-poppler-qt from yaourt appears to solve this issue for me as well:

yaourt -S python-poppler-qt5

**Comment by ExecutorElassus** [comment] 2017-01-11 22:33
not sure if this is a separate issue, but frescobaldi-2.19.0 segfaults on startup with python-poppler-qt4 and the new sip ABI. I cannot recompile python-poppler-qt4, either: compilation fails as per [this bug](https://bugs.gentoo.org/show_bug.cgi?id=604472).

**Comment by ExecutorElassus** [comment] 2017-01-17 10:58
I'm encountering another error when I try to compile python-poppler-qt5 from git (I run gentoo, and this isn't in our repositories yet). Running 'python3 setup.py build' returns the following error:

> $ python3 setup.py build
> running build
> running build_ext
> building 'popplerqt5' extension
> /usr/bin/sip -I /usr/share/sip -t POPPLER_V0_28_0 -c build/temp.linux-x86_64-3.5 -b build/temp.linux-x86_64-3.5/poppler-qt5.sbf -I /usr/share/sip/PyQt5 -t WS_X11 -t Qt_5_7_1 poppler-qt5.sip
> sip: Deprecation warning: poppler-qt5.sip:1: %Module version numbers are deprecated and ignored
> creating build/temp.linux-x86_64-3.5/build
> creating build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5
> x86_64-pc-linux-gnu-g++ -pthread -fPIC -I/usr/include/poppler/qt5 -I/usr/include/poppler -I/usr/include/python3.5m -I/usr/include/python3.5m -I/usr/include/qt5 -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtXml -c build/temp.linux-x86_64-3.5/sippopplerqt5cmodule.cpp -o build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5/sippopplerqt5cmodule.o
> In file included from /usr/include/qt5/QtCore/qglobal.h:83:0,
>                  from /usr/include/qt5/QtCore/qmetatype.h:44,
>                  from /usr/include/qt5/QtCore/QMetaType:1,
>                  from build/temp.linux-x86_64-3.5/sipAPIpopplerqt5.h:12,
>                  from build/temp.linux-x86_64-3.5/sippopplerqt5cmodule.cpp:7:
> /usr/include/qt5/QtCore/qcompilerdetection.h:562:6: error: #error Qt requires a C++11 compiler and yours does not seem to be that.
>  #    error Qt requires a C++11 compiler and yours does not seem to be that.
> 
> 

and then a whole bunch of errors about undefined functions and missing C++11 support. Thing is, I've been using gcc-5* for over a year now, and C++11 is the default. The gentoo forum suggests that "it might be solved by running `append-cxxflags -std=c++11` in src_prepare using flag-o-matic.eclass" (the flag-o-matic.eclass is apparently an internal tool in gentoo's base system for appending flags). But I'm not sure how to do that. They also suggest it's a problem with the package itself.

Is anybody else getting errors about missing C++11 support? How did you get around it?

**Comment by ExecutorElassus** [comment] 2017-01-18 09:57
Update: I've built a package script for gentoo to try to get around the problem with CXXFLAGS, and now I encounter the following error when compiling:

> In file included from /var/tmp/portage/dev-python/python-poppler-qt5-9999/work/python-poppler-qt5-9999-python3_5/temp.linux-x86_64-3.5/sippopplerqt5QList0600QLinkedList0100QPointF.cpp:7:0:
> types.sip: In function ‘int convertTo_QList_0600QLinkedList_0100QPointF(PyObject*, void**, int*, PyObject*)’:
> /var/tmp/portage/dev-python/python-poppler-qt5-9999/work/python-poppler-qt5-9999-python3_5/temp.linux-x86_64-3.5/sipAPIpopplerqt5.h:1762:67: error: ‘sipWrapperType {aka struct _sipWrapperType}’ has no member named ‘type’
>  #define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->type, (s))
>                                                                    ^
> types.sip:231:7: note: in expansion of macro ‘sipReleaseInstance’
>        sipReleaseInstance(t, sipClass_TYPE, state);
>        ^
> /var/tmp/portage/dev-python/python-poppler-qt5-9999/work/python-poppler-qt5-9999-python3_5/temp.linux-x86_64-3.5/sipAPIpopplerqt5.h:1762:67: error: ‘sipWrapperType {aka struct _sipWrapperType}’ has no member named ‘type’
>  #define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->type, (s))
>                                                                    ^
> types.sip:236:5: note: in expansion of macro ‘sipReleaseInstance’
>      sipReleaseInstance(t, sipClass_TYPE, state);
>      ^
> error: command 'x86_64-pc-linux-gnu-g++' failed with exit status 1

Can you let me know what might be causing this error? Is this more ABI incompatibility?

**Comment by prabhanshuguptagit** [comment] 2017-03-04 20:29
Having issues running frescobaldi after building and installing python-poppler-qt5. Even on manually building it from the repo leads to a segfault on running frescobaldi. 
```
~/frescobaldi$ python3 frescobaldi
Segmentation fault (core dumped)
```

Here's my versions without installing python-poppler-qt.
```
Frescobaldi: 3.0.0
Python: 3.5.2
python-ly: 0.9.5
Qt: 5.8.0
PyQt: 5.8
sip: 4.19.1
poppler: unknown
python-poppler-qt: unknown
OS: Linux-4.8.0-36-generic-x86_64-with-Ubuntu-16.04-xenial
```

Everything works just fine until I install this package.  I'm building python-poppler-qt5==0.24.2.

**Comment by fedelibre** [comment] 2017-07-13 09:10
For the records, `python3-poppler-qt5` package is now present in Fedora 26, released a few days ago.

**Comment by lar0sa** [comment] 2017-09-23 03:59
Hi all I am getting a very similar error in 
Ubuntu 17.04, 4.10.0-35-generic
Lilypond 2.18.2-7 
Frescobaldi 3.0.0~git20161001.0.eec60717+ds1-2
python 2.7.13-2
Is there a new way around this issue?
best,
Jaime

Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/musicview/pointandclick.py", line 44, in links
    return _cache[document]
  File "/usr/lib/python3.5/weakref.py", line 394, in __getitem__
    return self.data[ref(key)]
KeyError: <weakref at 0x7f15a9471408; to 'Document' at 0x7f15a9452f78>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/musicview/widget.py", line 116, in openDocument
    self._links = pointandclick.links(document)
  File "/usr/share/frescobaldi/frescobaldi_app/musicview/pointandclick.py", line 54, in links
    t = textedit.link(link.url())
  File "/usr/share/frescobaldi/frescobaldi_app/textedit.py", line 48, in link
    m = textedit_match(url)
TypeError: expected string or bytes-like object
