### ISSUE TITLE
Icons aren't aligned with installer background image

### ISSUE THREAD

**Issue by SSteve** [wbsoft/frescobaldi#794] opened 2016-01-18 04:03 UTC
On a 27" retina iMac running OS X 10.11.2, the icons aren't aligned with the installer disk background image.
![screen shot 2016-01-17 at 8 01 07 pm](https://cloud.githubusercontent.com/assets/523551/12382988/4e253670-bd55-11e5-81dd-b28b58975121.png)

**Comment by dliessi** [comment] 2016-04-25 10:24
The DMG for the next version of Frescobaldi will include the fix.
I confirmed that the issue is fixed on OS X 10.10.

**Closed** 2016-04-25 10:23 UTC
Labels: macosx

**Comment by dliessi** [comment] 2016-04-25 10:25
@wbsoft I pushed directly to the v2.x and master branches, because this is completely independent from the Py2/3-Qt4/5 issue and also from Frescobaldi itself, so I thought this didn't deserve a pull request.
