### ISSUE TITLE
Re-embedding log window into main window

### ISSUE THREAD

**Issue by jeanas** [wbsoft/frescobaldi#1452] opened 2022-08-29 21:00 UTC
I've accidentally taken my log window out of the main window.

![image](https://user-images.githubusercontent.com/37271310/187297448-e4dab922-ef8f-40e9-b5cc-e0785adadf20.png)

Now, I'd like it back at the bottom left of the main window. When I was on Ubuntu, it used to work to "drag" it near the bottom left. That would "insert" it back into the left part of the screen with the source code. Now I am on Fedora and this doesn't work.

- Is there a way to do this?
- Is it expected that dragging the window doesn't work on Fedora?

**Comment by fedelibre** [comment] 2022-08-31 19:05
No, it should work on Fedora.

I'm now on my laptop, where I have Fedora Silverblue installed, so I'm using the Frescobaldi flatpak and I can drag the window out and back to its place very easily.
Perhaps the issue is limited to the RPM package (which I suppose you're using)? Or maybe some configuration you have? Are you using Wayland, right?
Next Monday I'll be back to office, where I have a desktop with a regular Fedora installed.  I'll see if the RPM package works fine.

**Comment by fedelibre** [comment] 2022-09-02 09:18
I'm now on Fedora 36 Workstation and I can reproduce your problem if I use the RPM package, currently at version 3.1.3 (but 3.2 is in testing).

Do you see org.frescobaldi.python3 as application name in the top bar?
I think the problem with the application windows is caused by some mismatch in the application name. See this screenshot:

![Schermata del 2022-09-02 11-07-27](https://user-images.githubusercontent.com/1644647/188107417-256eb9b7-704c-4dcb-8d08-d08c7fb38ed8.png)

**Comment by fedelibre** [comment] 2022-09-02 09:36
Here:

![Schermata del 2022-09-02 11-28-57](https://user-images.githubusercontent.com/1644647/188110954-6fa0fa71-9e97-49ef-81f2-0b3175ec92ce.png)

**Comment by fedelibre** [comment] 2022-09-06 07:22
Ok, now I remember. This is a duplicate of #1273.
Launching frescobaldi this way "fixes" the problem:

```
QT_QPA_PLATFORM=xcb frescobaldi
```

Frescobaldi flatpak contains an option to run it this way by default.

**Closed as not planned** 2022-09-19 21:45 UTC
