### ISSUE TITLE
Frescobaldi crashes during startup if SVG is activated (Windows)

### ISSUE THREAD

**Issue by 19joho66** [wbsoft/frescobaldi#848] opened 2016-08-19 11:46 UTC
I've build the setup for windows and the installation works well. I now recognized that if I activate the SVG-View under tools and close the program, Frescobaldi will crash during the next startup. You see the splash screen for a short time and then it is gone.
If I delete the state Key in the registry (HHKEY_CURRENT_USER\software\Frescobaldi\frescobaldi\mainwindow\state) it will start up again. 
Do you encounter similar problems under Linux?

**Comment by wbsoft** [comment] 2016-08-25 12:07
Thanks for reporting. I can't reproduce under Linux, but this is a serious issue, as a casual user would not be able to get Frescobaldi running anymore :)

**Comment by 19joho66** [comment] 2017-02-02 11:12
I've been into this issue a bit more. First I tried to use Qt5.7 which didn't work because QWebKit is deprecated in that Version. So I changed to the new QWebEngine which worked in general, but you couldn't reload the page in the SVG window (point and click was broken after reload) After some time, I found out, that especially in the SVG handling something is broken in the Qt5.7 Version.
Therefore I changed back to Qt5.6 but still using QWebEngine which seems to be working. No more crashes and point and click works fine.
I'm not sure if you plan to change to the newer QWebEngine and Qt5.6. If you do, this could be the right solution for Windows.

**Comment by 19joho66** [comment] 2017-02-24 11:05
Next update!
I just discovered, that the QWebKit has been resurected for Qt5.8. So I now changed to Qt5.8 and am able to use the original source code again.  Also the SVG viewer seem to work with this. Therefore there seems to be no need to change to QWebEngine after all

**Comment by uliska** [comment] 2018-07-19 22:35
Is this still relevant? Can't we close this issue (can always be reopened when anyone still/again has problems.

**Closed** 2018-07-20 11:02 UTC
Labels: critical, windows
