### ISSUE TITLE
ABC import: IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by wbsoft** [wbsoft/frescobaldi#633] opened 2015-03-08 06:27 UTC
Reported by a user:
```
Frescobaldi: 2.18

Python: 2.7.9 -- Qt: 4.8.6 -- PyQt4: 4.11.3 -- sip: 4.16.6
python-ly: 0.9
poppler: unknown -- python-poppler-qt4: unknown
OS: Darwin-14.1.0-x86_64-i386-64bit

Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/file_import/__init__.py", line 65, in importAll
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/file_import/__init__.py", line 90, in openDialog
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/file_import/__init__.py", line 153, in openAbcDialog
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/file_import/__init__.py", line 161, in runImport
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/file_import/abc.py", line 91, in run_command
IOError: [Errno 2] No such file or directory: u'/var/folders/x0/800486lw8xj7t90059bpdlb00000gn/T/frescobaldi-YM6clK/tmp7QigOs/-'

Optionally describe below what you were doing:

Tried to import an ABC file.
```

**Comment by PeterBjuhr** [comment] 2015-03-08 08:45
This is related to #621. It seems the workaround doesn't work on Darwin.

**Comment by dliessi** [comment] 2015-03-08 09:26
> This is related to #621. It seems the workaround doesn't work on Darwin.

Not really: ABC import works perfectly on Mac.

This is a duplicate of #554: for some reason on these machines Frescobaldi cannot create temporary files.
@wbsoft: is this the same user?
In both cases the user was running OS X 10.10 (Yosemite, Darwin 14).

Again, we need to know if this is a temporary glitch or a reproducible error.

**Comment by wbsoft** [comment] 2015-03-08 09:35
It certainly is not a duplicate of #554. In #554 the temp folder is not found. Here, the `-` file is not found (i.e. probably not created).

(It was not the same user).

**Comment by dliessi** [comment] 2015-03-08 09:45
Ok, sorry, I tested with the app bundle from the DMG and indeed I got the same error.

**Comment by PeterBjuhr** [comment] 2015-03-08 10:11
@dliessi do you need to create a new app bundle to test it again?

**Comment by dliessi** [comment] 2015-03-08 12:48
Yes, because it was a problem only with the fully standalone application bundle.
I'm doing it now.

**Comment by dliessi** [comment] 2015-03-08 14:28
Ok, there's some bigger problem here: not only ABC import still gives the same error about temporary file/directory (I'm still convinced that this issue is related to #554, although I still cannot reproduce the latter), but I noticed that also MusicXML and MIDI imports do not work, complaining that some Python modules cannot be imported.

I'm sorry: I had wrongly assumed that the import issues we solved were orthogonal to the differences between command-line/lightweight-app/standalone-app, so I didn't test thoroughly with the fully standalone application.

I'll investigate these issues, but for the moment I'm going to add a note to the release page, stating that the imports are broken in the prebuilt application.

**Comment by dliessi** [comment] 2015-03-08 14:38
> I had wrongly assumed that the import issues we solved were orthogonal to the differences between command-line/lightweight-app/standalone-app, so I didn't test thoroughly with the fully standalone application.

To clarify: most of the differences so far were between command-line on one side and lightweight-app/standalone-app on the other side.
Having successfully tested the changes with the lightweight-app I had wrongly assumed that they worked also with the standalone-app.
The issues we're facing here instead are between command-line/lightweight-app on one side and standalone-app on the other side.

**Comment by PaulMorris** [comment] 2015-03-08 15:21
Not sure if it's related, but I also tried convert-ly and got the following error. (I'm the user who originally reported the issue with importing an abc file, so this is on the same osx configuration.)

'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "/Applications/LilyPond.app/Contents/Resources/bin/convert-ly", line 24, in <module>
    import os
ImportError: No module named os

The document has not been changed.

**Comment by wbsoft** [comment] 2015-03-08 15:25
> I'm still convinced that this issue is related to #554, although I still cannot reproduce the latter

Indeed, you may be right! I thought that, because the full filename was given in the error, the temp folder was created successfully. But that might not have been the case. 

I'm sorry I can't help here, I don't own any OS X equipment.

**Comment by dliessi** [comment] 2015-03-08 16:16
> Not sure if it's related, but I also tried convert-ly [...]

I don't know if it is related to the ABC problem, but it is definitely the same problem of MIDI and MusicXML imports.

I changed the code that constructs the command line in order to use the system Python, but for some reason when it is run from the standalone application the system Python cannot import its own modules.

**Comment by PeterBjuhr** [comment] 2015-03-09 09:21
So if I understand it correctly what we have here is the import error from #589, but when using abc2ly we instead get an `IOError` because the file is unsuccessfully opened before the import error can be shown.

**Comment by PeterBjuhr** [comment] 2015-03-09 09:58
One question that comes to mind: for those LilyPond tools that are written in Python, would it be better to run them as imported packages instead as a command-line tools?

**Comment by wbsoft** [comment] 2015-03-09 10:06
It would be nice to be able to import them, but I think it's better to run them as standalone executable commands. Or, if that is not possible, run them using the python interpreter bundled with that particular LilyPond version.

**Comment by dliessi** [comment] 2015-03-09 11:02
> So if I understand it correctly what we have here is the import error from #589, but when using abc2ly we instead get an IOError because the file is unsuccessfully opened before the import error can be shown.

Yes, and indeed your fix exposed the module import error also for ABC.

> It would be nice to be able to import them, but I think it's better to run them as standalone executable commands. Or, if that is not possible, run them using the python interpreter bundled with that particular LilyPond version.

The latter is not possible, since on Mac the Python interpreter included in LilyPond lacks many modules and is difficult to invoke directly from outside LilyPond.

See the comments in [`system_python`](https://github.com/dliessi/frescobaldi/blob/master/frescobaldi_app/macosx/__init__.py#L52).
For those reasons the system Python interpreter is currently invoked, and this works perfectly when Frescobaldi is run from command line or as a lightweight application bundle.
But when it is run as a standalone application bundle the system Python cannot find its own modules.

I don't understand why this happens, but I think I found a hint to where the problem is.
Currently testing.

**Comment by PeterBjuhr** [comment] 2015-03-09 11:16
>>So if I understand it correctly what we have here is the import error from #589, but when using abc2ly we instead get an IOError because the file is unsuccessfully opened before the import error can be shown.

>Yes, and indeed your fix exposed the module import error also for ABC.

I close this and reopen #589 then. I hope you don't mind!

**Closed by PeterBjuhr** 2015-03-09 11:16 UTC
Labels: macosx

**Comment by wbsoft** [comment] 2015-03-09 13:13
> > It would be nice to be able to import them, but I think it's better to run them as standalone executable commands. Or, if that is not possible, run them using the python interpreter bundled with that particular LilyPond version.

> The latter is not possible, since on Mac the Python interpreter included in LilyPond lacks many modules and is difficult to invoke directly from outside LilyPond.

How are the LilyPond scripts (such as `convert-ly`) called then on Mac OS X (how would you use them normally, not via Frescobaldi) ?

**Comment by dliessi** [comment] 2015-03-09 13:26
> How are the LilyPond scripts (such as convert-ly) called then on Mac OS X (how would you use them normally, not via Frescobaldi) ?

With the system Python.

> Frescobaldi should be able to run them, just as a cli user would, I think.

This is indeed what I'm trying to achieve.

**Comment by wbsoft** [comment] 2015-03-09 17:19
thanks for the enlightment! I feel powerless, with no mac :-(
