### ISSUE TITLE
macOS installation failure to build poppler

### ISSUE THREAD

**Issue by kfeuerherm** [wbsoft/frescobaldi#975] opened 2017-06-23 15:25 UTC
Spent a day trying to instal using Homebrew before seeing the note that this can't be done currently. Switched to MacPorts.

Ultimately failed to build poppler and also issued warning. Not sure how to fix this.

Thanks.

Log file attached. Warnings from Terminal window follow:

Error: Failed to build poppler: command execution failed
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_graphics_poppler/poppler/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port frescobaldi failed
--->  Some of the ports you installed have notes:
  python35 has the following notes:
    To make this the default Python or Python 3 (i.e., the version run by the
    'python' or 'python3' commands), run one or both of:
    
        sudo port select --set python python35
        sudo port select --set python3 python35
    
    ##############################################################
    # IF YOU ARE USING PYTHON FROM THE TERMINAL, PLEASE INSTALL:
    #   py35-readline
    # TO AVOID A LIBEDIT / PYTHON INTERACTION ISSUE.
    # REF: https://trac.macports.org/ticket/48807
    ##############################################################
  rsync has the following notes:
    To use the rsyncd server you must copy /opt/local/etc/rsyncd.conf.example to
    rsyncd.conf and add your modules there. See 'man rsyncd.conf' for more
    information.

[poppler-log.txt](https://github.com/wbsoft/frescobaldi/files/1098277/poppler-log.txt)

**Comment by dliessi** [comment] 2017-06-25 13:59
Poppler builds and runs correctly here with MacPorts.
Assuming that the command you tried was `sudo port install frescobaldi`, please try
```
sudo port clean poppler
sudo port selfupdate
sudo port install frescobaldi
```
If it still fails, please open a ticket at [MacPorts' tracker](https://trac.macports.org/wiki/Tickets) attaching the log file.

Anyway, I'm closing this issue since it is not a bug in Frescobaldi.

**Closed by dliessi** 2017-06-25 13:59 UTC

**Comment by kfeuerherm** [comment] 2017-06-26 12:36
Thanks, I thought there might be an issue with the installation script.

Seems to have worked after a suggested update of outdated modules also. Your help is appreciated.

KF
