### ISSUE TITLE
Error when exporting to MusicXML

### ISSUE THREAD

**Issue by martinjaroszewicz** [wbsoft/frescobaldi#784] opened 2015-11-30 21:41 UTC
Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/file_export/__init__.py", line 64, in exportMusicXML
  File "ly/musicxml/lymus2musxml.pyc", line 93, in parse_text
  File "ly/musicxml/lymus2musxml.pyc", line 106, in parse_document
  File "ly/musicxml/lymus2musxml.pyc", line 120, in parse_tree
  File "ly/musicxml/lymus2musxml.pyc", line 132, in parse_nodes
  File "ly/musicxml/lymus2musxml.pyc", line 512, in SchemeItem
  File "ly/musicxml/ly2xml_mediator.pyc", line 656, in new_ottava
ValueError: invalid literal for int() with base 10: 'mixed'

Sorry, I cannot attach my files.

**Comment by PeterBjuhr** [comment] 2015-12-01 19:41
I guess this is a duplicate of https://github.com/wbsoft/python-ly/issues/50 and can be closed!

**Closed by PeterBjuhr** 2015-12-01 19:41 UTC
