### ISSUE TITLE
Problem with LilyPond versions stored in the config file

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#1089] opened 2018-08-06 07:32 UTC
Reported by @fedelibre during discussion of PR #1075 (https://github.com/wbsoft/frescobaldi/pull/1075#issuecomment-410152026 and following (note: other subtopics interspersed).

There seems to be something wrong with the way registered LilyPond versions are stored in the configuration file, and consequently how the default version is retrieved (for use in the "show fonts" dialog, regular compilation is fine).

@uliska 's first impression is that it's simply related to the specific installation, but we should try to sort out if that's true or if we have a bug here.

**Comment by fedelibre** [comment] 2018-08-12 21:37
It's defintely related to my old frescobaldi.conf file.
I change its name to make a backup and launched again Frescobaldi to let it create a new frescobaldi.conf, which seems to work fine. I'll keep it using and see if it breaks.

I did not debug the old file too much. I tried removing the lines related to old installations but did not help.

**Comment by fedelibre** [comment] 2018-08-18 18:56
Weird... I've now tested again the old file and it's working fine. I just tried changing autoversion from true to false, since that was the main difference between the two conf files in the lilypond_settings section. Then I changed it back to true. It just works and I doubt this change has anything to do with it.

I'll keep the issue open and see if I can reproduce it again.

**Comment by uliska** [comment] 2018-10-09 09:48
@fedelibre what's the state of this, couldn't we close the issue?

**Comment by fedelibre** [comment] 2018-10-09 11:35
I think so, but I cannot verify at the moment since I have another error. I'll report it in a minute.

**Comment by fedelibre** [comment] 2018-10-10 07:29
Yes, let's close it, since I cannot reproduce it anymore.

**Closed by fedelibre** 2018-10-10 07:29 UTC
Labels: defect
