### ISSUE TITLE
Engrave Preview Problem

### ISSUE THREAD

**Issue by andremsantanna** [wbsoft/frescobaldi#705] opened 2015-07-08 05:47 UTC
I'm a Fedora 22 user with Frescobaldi 2.18.1 and Lilypond 2.19. I'm having an issue when i try to engrave a score. It seems to fail when it tries to generate a pdf.

Layout output to `duba.ps'...
Converting to`./duba.pdf'...
warning: `(gs -q -dSAFER -dDEVICEWIDTHPOINTS=595.28 -dDEVICEHEIGHTPOINTS=841.89 -dCompatibilityLevel=1.4 -dNOPAUSE -dBATCH -r1200 -sDEVICE=pdfwrite -sOutputFile=./duba.pdf -c.setpdfwrite -fduba.ps)' failed (256)

fatal error: failed files: "/home/marsan/Documentos/Partituras/Coral/Duba/duba.ly"

What is wrong?

Thanks.

**Comment by uliska** [comment] 2015-07-08 05:56
This is a known LilyPond issue, not with Frescobaldi.
Sorry but I don't know what the current state is.

Urs

Am 8. Juli 2015 07:47:58 MESZ, schrieb andremsantanna <notifications@github.com>:
>I'm a Fedora 22 user with Frescobaldi 2.18.1 and Lilypond 2.19. I'm
>having an issue when i try to engrave a score. It seems to fail when it
>tries to generate a pdf.
>
>Layout output to `duba.ps'...
>Converting to `./duba.pdf'...
>warning: `(gs -q -dSAFER -dDEVICEWIDTHPOINTS=595.28
>-dDEVICEHEIGHTPOINTS=841.89 -dCompatibilityLevel=1.4 -dNOPAUSE -dBATCH
>-r1200 -sDEVICE=pdfwrite -sOutputFile=./duba.pdf -c.setpdfwrite
>-fduba.ps)' failed (256)
>
>fatal error: failed files:
>"/home/marsan/Documentos/Partituras/Coral/Duba/duba.ly"
>
>What is wrong?
>
>Thanks.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/wbsoft/frescobaldi/issues/705

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by PeterBjuhr** [comment] 2015-07-08 08:52
I forwarded this to the [LilyPond users mailing list](http://lists.gnu.org/archive/html/lilypond-user/2015-07/msg00079.html).

It was quickly responded that this issue is fixed for LilyPond 2.19.22.

**Comment by uliska** [comment] 2015-07-08 09:29
> This is a known LilyPond issue, not with Frescobaldi.

I have to revoke that opinion. It *can* be a Frescobaldi issue. I just downloaded and installed LilyPond 2.19.22. Compiling a file from the command line works fine with *either 2.19.21 or 2.19.22*. But when I compile them directly through Frescobaldi I get the following (basically the same) error:

```
Layout output to `/tmp/lilypond-NzD1AH'...
Converting to `testcrash.pdf'...
warning: `(gs -q -dSAFER -dDEVICEWIDTHPOINTS=595.28 -dDEVICEHEIGHTPOINTS=841.89 -dCompatibilityLevel=1.4 -dNOPAUSE -dBATCH -r1200 -sDEVICE=pdfwrite -sOutputFile=testcrash.pdf -c.setpdfwrite -f/tmp/lilypond-NzD1AH)' failed (256)

fatal error: failed files: "/home/uliska/Schreibtisch/testcrash.ly"
Exited with return code 1.
```

The `--verbose` option tells more:
```
Converting to `testcrash.pdf'...
Invoking `gs -dSAFER -dDEVICEWIDTHPOINTS=595.28 -dDEVICEHEIGHTPOINTS=841.89 -dCompatibilityLevel=1.4 -dNOPAUSE -dBATCH -r1200 -sDEVICE=pdfwrite -sOutputFile=testcrash.pdf -c.setpdfwrite -f/tmp/lilypond-QiGEUo'...

gs: Interpreter revision (906) does not match gs_init.ps revision (915).
warning: `(gs -dSAFER -dDEVICEWIDTHPOINTS=595.28 -dDEVICEHEIGHTPOINTS=841.89 -dCompatibilityLevel=1.4 -dNOPAUSE -dBATCH -r1200 -sDEVICE=pdfwrite -sOutputFile=testcrash.pdf -c.setpdfwrite -f/tmp/lilypond-QiGEUo)' failed (256)

/home/uliska/blob/software/lilypond/releases/2.19.22/usr/share/lilypond/current/scm/lily.scmfatal error: failed files: "/home/uliska/Schreibtisch/testcrash.ly"
Exited with return code 1.
```

So obviously there are two different versions of GhostScript (`gs`) around, and the one called up when compiling the file from within Frescobaldi doesn't match the one expected by LilyPond's postscript code.

I think the solution lies in the `~/bin/lilypond` wrapper script around LilyPond:

```bash
#!/bin/sh
me=`basename $0`
export LD_LIBRARY_PATH="/home/uliska/lilypond/usr/lib"
exec "/home/uliska/lilypond/usr/bin/$me" "$@"
```

This hard-codes the library path to inside the (binary) LilyPond distribution. 
When I call LilyPond's executable directly instead of through the wrapper script I get the same errors as with Frescobaldi.

Obviously Frescobaldi should also set this environment variable if necessary. I have the start of a solution available: Frescobaldi should execute the line

```python
os.environ['LD_LIBRARY_PATH'] = "/path/to/lilypond/executable/../lib"
```
whenever LilyPond is called with its full path.
I verified that the compilation then works, but I could only hard-code it into `engrave/command.py-> defaultJob()`. I don't really see how this should be integrated in the whole Engrave infrastructure.

**Comment by PeterBjuhr** [comment] 2015-07-08 19:24
Good catch! I don't fully comprehend this but although this may be a good workaround in your system it may not be appropriate as a generic solution in all systems so it should be carefully considered. 

One question, can't you setup Frescobaldi so the same wrapper script is used instead of using the executable directly (as you state as the problem)?

**Comment by wbsoft** [comment] 2015-07-08 19:31
you should indeed run the LilyPond wrapper script, if using the binary LilyPond distributions. The one in `bin` . Which would also be called directly when installing a binary LilyPond distribution in the path.

**Comment by uliska** [comment] 2015-08-03 08:36
> you should indeed run the LilyPond wrapper script, if using the binary LilyPond distributions. The one in bin . Which would also be called directly when installing a binary LilyPond distribution in the path

I just thought about this again, and I think it's not enough to call the wrapper script.
I have numerous binary installations around and want to use them from Frescobaldi, so I have them in different installation directories and direct Frescobaldi to their executables. The wrapper script in `~/bin` can only point to one specific version. 

I think we should urgently fix this because it means that newer LilyPond versions can currently only be used (on certain systems?) when installed as the only LilyPond.

**Comment by uliska** [comment] 2015-08-03 08:37
I added the `critical` label because I feel it is. But you may of course consider this too much and revert that, @wbsoft.

It has to be noted that this isn't a genuine Frescobaldi shortcoming but something that changed in LilyPond in a recent version, and we should try to accomodate the new situation.

**Comment by PeterBjuhr** [comment] 2015-08-05 19:31
I assume then you can run all the LilyPond installations externally but not from within Frescobaldi. Can you/have you debug(ged) exactly what is the difference in the call of LilyPond in the two cases?

**Comment by uliska** [comment] 2015-08-05 19:50
> I assume then you can run all the LilyPond installations externally but not from within Frescobaldi.

Nearly. I can run them when calling the installation's wrapper script and have that point to the given installation.
[The installation script installs LilyPond in `~/lilypond` and places the wrapper script in `~/bin/lilypond`. I then move the lilypond directory somewhere else and create a symlink to that new location. This way I can switch between installations by changing that symlink.]

> Can you/have you debug(ged) exactly what is the difference in the call of LilyPond in the two cases?

The difference is that the wrapper script executes `export LD_LIBRARY_PATH="~/lilypond/usr/lib"`. Actually I have explained this above in https://github.com/wbsoft/frescobaldi/issues/705#issuecomment-119519218. I did implement what I suggested in that comment as a test, and it worked. It's just that I hard-coded it into the construction of the command line that won't work as a proper solution. But basically that's what we need to do: add that library path to LilyPond's execution environment. This will ensure that LilyPond will use the built-in version of Ghostscript (?) and not an arbitrary one that is present on the user's system.

**Comment by PeterBjuhr** [comment] 2015-08-05 20:31
>I can run them when calling the installation's wrapper script and have that point to the given installation.
>[The installation script installs LilyPond in ~/lilypond and places the wrapper script in ~/bin/lilypond. I then move the lilypond directory somewhere else and create a symlink to that new location. This way I can switch between installations by changing that symlink.]

So you have to change the link manually to make it point at the specific version!?

>>Can you/have you debug(ged) exactly what is the difference in the call of LilyPond in the two cases?

>The difference is that the wrapper script executes export LD_LIBRARY_PATH="~/lilypond/usr/lib". 

If I read you correctly the difference is that you don't use the wrapper script (~/bin/lilypond) in Frescobaldi, if you'd done that the result would have been the same!??

>Actually I have explained this above in #705 (comment). I did implement what I suggested in that comment as a test, and it worked. It's just that I hard-coded it into the construction of the command line that won't work as a proper solution. But basically that's what we need to do: add that library path to LilyPond's execution environment. This will ensure that LilyPond will use the built-in version of Ghostscript (?) and not an arbitrary one that is present on the user's system.

I'm very sorry if I'm misunderstanding this, but what you're describing is not a bug but a feature request - you want Frescobaldi to do what the wrapper script is doing but with the added bonus that you don't have to change the link!???

(As such I cannot at this point overview if this can be implemented and what the possible side-effects are.)

**Comment by uliska** [comment] 2015-08-05 20:43
> So you have to change the link manually to make it point at the specific version!?

Yes, that's my personal set-up. Actually I did never need that because I could select versions from within Frescobaldi.

>>     The difference is that the wrapper script executes export LD_LIBRARY_PATH="~/lilypond/usr/lib".

> If I read you correctly the difference is that you don't use the wrapper script (~/bin/lilypond) in Frescobaldi, if you'd done that the result would have been the same!??

Yes, exactly.

> I'm very sorry if I'm misunderstanding this, but what you're describing is not a bug but a feature request - you want Frescobaldi to do what the wrapper script is doing but with the added bonus that you don't have to change the link!???

No, that's not really true.
Frescobaldi lets me select any number of LilyPond versions by choosing their binaries. That's the point of Frescobaldi's LilyPond version handling. And up to (some-point-between-2.19.17-and-2.19.21) this worked without a problem. But due to some change in LilyPond (I think it had to do with updating a Ghostscript or Pango version) this doesn't work anymore (at least on all systems). *Now*, if you don't call LilyPond through its wrapper script it can call the wrong Ghostscript executable.

So, in a way you're right that this is not a bug in Frescobaldi. And it isn't a real bug in LilyPond either. But it is a change in behaviour of LilyPond that should be handled by Frescobaldi. It *must* still be possible to register arbitrary LilyPond versions through its executable and not through the wrapper script (i.e. the default `~/bin/lilypond` path).

The wrapper script approach doesn't really support multiple LilyPond versions/paths, so the solution should be what I sketched: Adding the library path to the shell's environment, and this shouldn't be very complicated, and especially it shouldn't have any side effects as it only affects the current run.

**Comment by PeterBjuhr** [comment] 2015-08-05 21:19
I still think you are expecting to much - the limitations of LilyPond are also the limitations of Frescobaldi at this point.

But your suggestion for improvement should of course be considered!

**Comment by uliska** [comment] 2015-08-05 22:40
I don't know how many users/systems are affected by that situation. But for those who are affected (e.g. me) this completely spoils the point of having alternative LilyPond versions available in Frescobaldi. For LilyPond it's not really a limitation because you can still simply install and use it.

I repeat that this change in LilyPond breaks an important functionality in Frescobaldi (choosing from an arbitrary number of installed LilyPond versions), so we have to respond to that change.

**Comment by wbsoft** [comment] 2015-09-26 06:01
I also install many different LilyPond binaries, but dont move the wrapper script. I just let Frescobaldi call e.g. `~/lilypond_bin/2.18.2/bin/lilypond`. I use the `--prefix` and `--batch` options of the binary LilyPond installers, like:

```
cd ~/lilypond_bin
mkdir 2.19.17-1
sh ~/downloads/lilypond-2.19.17-1.linux-x86.sh --batch --prefix 2.19.17-1/
```
That's all, and then I point Frescobaldi to `~/lilypond_bin/2.19.17-1/bin/lilypond`. The old Frescobaldi 1 could download and install LilyPond itself, and this functionality also should come in Frescobaldi 2 :-)

**Comment by uliska** [comment] 2017-05-09 07:04
The problem is still existant as LilyPond versions seem to move on differently than Ghostscript versions on different LInux platforms. Obviously it doesn't affect other OSes, so I'll apply my fix in https://github.com/wbsoft/frescobaldi/pull/926 and close this issue then.

**Closed** 2017-05-09 07:06 UTC
Labels: critical, defect
