### ISSUE TITLE
on Mac, when I launch Frescobaldi it does not show the document

### ISSUE THREAD

**Issue by wbsoft** [wbsoft/frescobaldi#603] opened 2015-01-29 17:04 UTC
Reported by a user:

> on Mac, when I launch Frescobaldi it does not show the document. I always have to go to " Window > New Window" to see the lilypond code and the music. Is there a workaround?

There was a reply by @philmassart : 

> That bug is found since some time now (and is linked, I think, to the mac implementation of the QT4 framework). The only other way now is to click once more on the Frescobaldi icon in the Dock since Frescobaldi is running

Can it be a Frescobaldi bug? It seems Frescobaldi is started but does not show or create a main window...

**Comment by dliessi** [comment] 2015-02-06 08:52
Duplicate of #428?

**Comment by dliessi** [comment] 2015-02-16 20:40
I'm closing this issue because I believe it is a...
> Duplicate of #428

**Closed by dliessi** 2015-02-16 20:40 UTC
Labels: macosx
