### ISSUE TITLE
Frescobaldi crashes during startup on MacOs Homebrew – NO MODULE NAMED SIP

### ISSUE THREAD

**Issue by grammaton** [wbsoft/frescobaldi#856] opened 2016-09-02 10:18 UTC
The same things on two different  Mac with `Homebrew 0.9.9` freshly updated && upgrade

```
$ frescobaldi
Traceback (most recent call last):
  File "/usr/local/Cellar/frescobaldi/2.19.0/libexec/bin/frescobaldi", line 7, in <module>
    import main
  File "/usr/local/Cellar/frescobaldi/2.19.0/libexec/lib/python2.7/site-packages/frescobaldi_app/main.py", line 26, in <module>
    import sip
ImportError: No module named sip
```

**Comment by dliessi** [comment] 2016-09-02 12:25
Duplicate of #778.
See caveats for `sip` in Homebrew.

**Closed by dliessi** 2016-09-02 12:25 UTC
