### ISSUE TITLE
osx: Launching Frescobaldi results in app running, but no main window shown

### ISSUE THREAD

**Issue by wbsoft** [wbsoft/frescobaldi#863] opened 2016-10-12 10:38 UTC
reported by a user:
> Frescobaldi: 2.19.0 -- Python: 2.7.11 -- python-ly: 0.9.4 -- Qt: 4.8.7 -- PyQt: 4.11.4 -- sip: 4.17 -- poppler: 0.39.0 -- python-poppler-qt: 0.24.0 -- OS: Darwin-15.6.0-x86_64-i386-64bit

> Since several iterations of Frescobaldi the first launching of the app results in app running, but not showing main window. One has to select something in the menu bar, and then the main window will be shown.

> OS X 10.11.6

**Comment by dliessi** [comment] 2016-10-12 10:45
Duplicate of #428. I added this as a comment.

**Closed by dliessi** 2016-10-12 10:45 UTC
Labels: macosx
