### ISSUE TITLE
Frescobaldi does not start in OpenSuse TW

### ISSUE THREAD

**Issue by jehojakim** [wbsoft/frescobaldi#1130] opened 2018-12-14 16:08 UTC
With the latest version of OpenSuse fresobaldi won't start anymore. 
When started from the terminal, I get

`Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/frescobaldi_app/plugin.py", line 79, in instance
    return _instances[cls][obj]
  File "/usr/lib64/python3.6/weakref.py", line 394, in __getitem__
    return self.data[ref(key)]
KeyError: <weakref at 0x7f183c099868; to 'type' at 0x55e9db06e8b8 (PanelManager)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/frescobaldi", line 11, in <module>
    main.main()                     # Parse command line, create windows etc
  File "/usr/lib/python3.6/site-packages/frescobaldi_app/main.py", line 247, in main
    win = mainwindow.MainWindow()
  File "/usr/lib/python3.6/site-packages/frescobaldi_app/mainwindow.py", line 128, in __init__
    self.createMenus()
  File "/usr/lib/python3.6/site-packages/frescobaldi_app/mainwindow.py", line 1010, in createMenus
    menu.createMenus(self)
  File "/usr/lib/python3.6/site-packages/frescobaldi_app/menu.py", line 61, in createMenus
    m.addMenu(menu_file(mainwindow))
  File "/usr/lib/python3.6/site-packages/frescobaldi_app/menu.py", line 96, in menu_file
    m.addMenu(snippet.menu.TemplateMenu(mainwindow))
  File "/usr/lib/python3.6/site-packages/frescobaldi_app/snippet/menu.py", line 139, in __init__
    self.addAction(self.tool().actionCollection.templates_manage)
  File "/usr/lib/python3.6/site-packages/frescobaldi_app/snippet/menu.py", line 59, in tool
    return panelmanager.manager(self.mainwindow()).snippettool
  File "/usr/lib/python3.6/site-packages/frescobaldi_app/panelmanager.py", line 36, in manager
    return PanelManager.instance(mainwindow)
  File "/usr/lib/python3.6/site-packages/frescobaldi_app/plugin.py", line 84, in instance
    result.__init__(obj)
  File "/usr/lib/python3.6/site-packages/frescobaldi_app/panelmanager.py", line 51, in __init__
    self.loadPanel("musicview.MusicViewPanel")
  File "/usr/lib/python3.6/site-packages/frescobaldi_app/panelmanager.py", line 86, in loadPanel
    __import__(module_name)
  File "/usr/lib/python3.6/site-packages/frescobaldi_app/musicview/__init__.py", line 56, in <module>
    from . import documents
  File "/usr/lib/python3.6/site-packages/frescobaldi_app/musicview/documents.py", line 32, in <module>
    import popplerqt5
ValueError: PyCapsule_GetPointer called with incorrect name
`
Frescobaldi version is 3.0.0.-2.1 from the TW-repo

What can be done/what can I do to solve this?

regards, jehojakim

**Comment by uliska** [comment] 2018-12-14 16:17
I know what "has" to be done, but I'm not sure what *you* can do about it. 
The problem is known and reoccurs every now and then, the problem is that one of the dependency packages (python-poppler-qt5 or python3-poppler-qt5) is not correctly recompiled against the correct Qt version.

It is possible to compile this package on your own, but I don't know how things work when Frescobaldi is installed from the distribution's repositories and packages.
Essentially it's a bug that should be reported to the maintainers of the python-poppler-qt5 package on your distribution. If you do that please refer them here to this issue.

**Comment by jehojakim** [comment] 2018-12-14 19:36
I entered https://bugzilla.opensuse.org/show_bug.cgi?id=1119580

**Comment by jehojakim** [comment] 2018-12-20 20:13
Solved in Tumbleweed snapshot 20181218.

**Comment by uliska** [comment] 2018-12-20 20:17
OK, that means we can close this issue here?

**Comment by jehojakim** [comment] 2018-12-20 20:21
Yes, for as far as I am concerned. And thanks for your advice!

**Closed** 2018-12-20 20:40 UTC
