### ISSUE TITLE
[Frescobaldi 2.17.2] RuntimeError: wrapped C/C++ object of type View has been deleted 

### ISSUE THREAD

**Issue by wbsoft** [wbsoft/frescobaldi#616] opened 2015-02-16 11:54 UTC
Reported by a user:

```
Frescobaldi: 2.17.2

Python: 2.7.9 -- Qt: 4.8.6 -- PyQt4: 4.11.3 -- sip: 4.16.5
OS: Darwin-10.8.0-i386-32bit

Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/preferences/__init__.py", line 111, in done
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/preferences/__init__.py", line 141, in saveSettings
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/signals.py", line 191, in emit
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/signals.py", line 298, in call
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/popplerview.py", line 67, in readSettings
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/qpopplerview/kineticscrollarea.py", line 127, in setScrollbarsVisible
RuntimeError: wrapped C/C++ object of type View has been deleted

Beschreiben Sie, was Sie getan haben (optional):
In Preferences bnei Lilypond-Einstellungen  den Standard-Ausgabe-Format von PDF in SVG gewechselt.
```

**Comment by dliessi** [comment] 2015-02-16 20:37
I cannot reproduce the error.
I tried switching back and forth from PDF to SVG both with and without open documents and also compiling a document after each change, but everything works as expected.

Maybe we need more details on what the user was doing.

I think that this might be a temporary glitch.

**Comment by dliessi** [comment] 2015-06-10 08:03
@wbsoft Do you think we can close this issue?

**Comment by wbsoft** [comment] 2015-06-11 16:36
I get sometimes this kind of error reports, where the deleted object sometimes differs... there is definitely something going on, always on darwin indeed...

**Comment by uliska** [comment] 2018-10-10 08:05
I experienced this too sometimes during development. In nearly all of the cases it was related to something (an exception) happening before a widget was properly disposed of.

I would say that generally this exception points to *some* kind of programming error (I suspect some kind of race condition). But I'm afraid if it's not reproducible  we can't pin it down.

Anyway, I think the original issue can be closed. If it happens again on any of the current branches please reopen or create a new one (we don't need the old issue's information then).

**Closed by uliska** 2018-10-10 08:05 UTC
Labels: macosx
